services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    environment:
      - REDIS_URL=redis://redis:6379
      - BACKEND_PORT=3000
      - POSTGRES_URL=${POSTGRES_URL}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - redis
      - rabbitmq
      - postgres
      - mongo

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - FRONTEND_PORT=5173
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI login
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_URL=amqp://rabbitmq

  worker:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  postgres-data:
  mongo-data: