services:
  backend:
    build: ./backend
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - BACKEND_PORT=3000
    depends_on:
      - redis
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - FRONTEND_PORT=5173
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI login
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq